version: '3.8'

services:
  postgres:
    container_name: container-pg
    image: postgres
    hostname: postgres
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-app
    ports:
      - "8080:8080"
    environment:
      # Database Configuration
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=admin
      - DB_PASSWORD=root
      - DB_NAME=test_db
      - DB_RECONN_RETRY=3
      - DB_TIME_WAIT_PER_TRY=5s

      # Server Configuration
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8080

      # NASA API Key
      - NASA_API_KEY=DEMO_KEY

      # Worker Configuration
      - WORKER_RUN_TIME=19:00
      - RUN_FETCHING_ON_START=false
      - NASA_API_URL=https://api.nasa.gov/planetary/apod

    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge